version: 2.1

jobs:
  web:
    docker:
      - image: circleci/node@12.19.0
    working_directory: ~/quicken-loans
    steps:
      - checkout
      - run:
        name: install-dependencies
        command: cd workspace && yarn install
      - run:
        name: angular-test
        command: cd workspace && yarn ng test --project=quicken-contacts --single-run --no-progress
      - store_artifacts:
        path: test-results.xml
        prefix: tests
      - run:
        name: angular-lint
        command: cd workspace && yarn lint -- --formatters-dir ./tslint-formatters --format junit -o tslint.xml
      - store_artifacts:
        path: tslint.xml
        prefix: lint
      - run:
          name: angular-build
          command: cd workspace && yarn ng build --project=quicken-contacts --prod --aot
workflows:
version: 2
concurrently:
    jobs:
    - web