version: 2.1
jobs:
  build:
    working_directory: ~/workspace
    docker:
      - image: cimg/node:15.4.0
    steps:
      - checkout
      - run: node --version
      - run:
          name: install-dependencies
          command: cd workspace && yarn install
      - run: yarn --version
      - run:
          name: angular-test
          command: cd workspace && yarn ng test --project=quicken-contacts --single-run --no-progress
      - store_artifacts:
          path: test-results.xml
          prefix: tests
      - run:
          name: angular-lint
          command: cd workspace && yarn lint -- --formatters-dir ./tslint-formatters --format junit -o tslint.xml
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
              - ~/.cache/yarn
              - ./node_modules
      - run:
          name: angular-build
          command: cd workspace && yarn ng build --project=quicken-contacts --prod --aot
      - store_artifacts:
          path: tslint.xml
          prefix: lint