version: 2.1
orbs:
    node: circleci/node@3.0.0
jobs:
  build:
    working_directory: ~/quicken-loans/workspace
    docker:
      - image: circleci/node:6-browsers
    steps:
      - checkout
      # - restore_cache:
      #     key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: install-dependencies
          command: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      # - save_cache:
      #     key: dependency-cache-{{ checksum "yarn.lock" }}
      #     paths:
      #       - ~/.cache/yarn
      #       - ./node_modules
      paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: angular-build
        #   command: yarn ng -- build --project=contacts --prod --aot --no-progress
          command: yarn ng build --project=contacts --prod --aot
      - run:
          name: angular-test
          command: yarn ng test --project=contacts --single-run --no-progress
      - store_artifacts:
          path: test-results.xml
          prefix: tests
      - run:
          name: angular-lint
          command: yarn lint -- --formatters-dir ./tslint-formatters --format junit -o tslint.xml
      - store_artifacts:
          path: tslint.xml
          prefix: lint