service: contacts
# app and org for use with dashboard.serverless.com
org: angulararchitecture
app: quicken-contacts

plugins:
  - serverless-plugin-typescript
  - serverless-plugin-optimize

provider:
  name: aws
  runtime: nodejs12.x
  region: us-west-1
  stage: ${opt:stage, 'dev'}
  environment:
    CONTACTS_TABLE_NAME: ${self:custom.ContactsTable.name}

functions:
  api:
    handler: ./apps/contacts/src/lambda.main
    events:
      - http:
          cors: true
          method: any
          path: /{any+}
      - http:
          cors: true
          method: any
          path: /
resources:
  Resources:
    ContactsTable: ${file(aws/contactsTable.yml):ContactsTable}
custom:
  ContactsTable:
    name: !Ref contactsTable
