service: contacts
# app and org for use with dashboard.serverless.com
org: angulararchitecture
app: quicken-contacts

plugins:
  - serverless-plugin-typescript
  - serverless-plugin-optimize

provider:
  name: aws
  tracing:
    apiGateway: true
  runtime: nodejs12.x
  region: us-west-1
  stage: ${opt:stage, 'dev'}
  environment:
    CONTACTS_TABLE_NAME: ${self:custom.ContactsTable.name}
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'dynamodb:Query'
        - 'dynamodb:PutItem'
        - 'dynamodb:GetItem'
        - 'dynamodb:UpdateItem'
        - 'dynamodb:DeleteItem'
      Resource: 'arn:aws:dynamodb:us-west-1:516631029472:table/ContactsTable-dev'
package:
  individually: true
functions:
  api:
    handler: ./apps/contacts/src/lambda.main
    events:
      - http:
          cors: true
          method: any
          path: /{any+}
      - http:
          cors: true
          method: any
          path: /
resources:
  Resources:
    ContactsTable: ${file(aws/contactsTable.yml):ContactsTable}
custom:
  ContactsTable:
    name: !Ref ContactsTable
